# Generated by Django 6.0.7 on 2026-07-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniGit', '0002_commit_repository_delete_commitactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
