# Generated by Django 6.0.7 on 2026-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniGit', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
