# Generated by Django 6.0.7 on 2026-07-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniGit', '0005_profile_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unigit_rating',
            field=models.IntegerField(default=0),
        ),
    ]
