# Generated by Django 6.0.7 on 2026-07-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniGit', '0006_profile_unigit_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('looking', 'В активном поиске'), ('busy', 'Занят')], default='free', max_length=20, verbose_name='Статус'),
        ),
    ]
