# Generated by Django 6.0.7 on 2026-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniGit', '0007_profile_contacts_profile_description_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_leetcode_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='leetcode_verify_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
